# Generated by Django 4.1.5 on 2023-11-27 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('property_type', models.CharField(max_length=255)),
                ('property_size', models.CharField(max_length=255)),
                ('many_doors', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'HomeSecurity',
                'verbose_name_plural': 'HomeSecurity',
                'ordering': ['-created_at'],
            },
        ),
    ]
