# Generated by Django 4.1.5 on 2023-12-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_homesecurity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
